
from vulcanforge.common.exceptions import ForgeError


class PasswordAlreadyUsedError(ForgeError):
    pass
